version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: aurora_motors_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn aurora_motors.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=aurora_motors_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=your_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  celery:
    build: .
    command: celery -A aurora_motors worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=aurora_motors_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=your_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  celery-beat:
    build: .
    command: celery -A aurora_motors beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_NAME=aurora_motors_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=your_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data:
  static_volume:
  media_volume: