# Generated by Django 5.2.4 on 2025-07-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Aurora Motors Pty Ltd', max_length=200)),
                ('company_email', models.EmailField(default='info@auroramotors.com', max_length=254)),
                ('company_phone', models.CharField(default='+61 2 1234 5678', max_length=20)),
                ('company_address', models.TextField(default='123 Motor Street, Sydney, NSW 2000, Australia')),
                ('site_name', models.CharField(default='Aurora Motors', max_length=200)),
                ('site_description', models.TextField(default='Premium Car Rental Service')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('booking_lead_time_hours', models.PositiveIntegerField(default=2)),
                ('booking_max_duration_days', models.PositiveIntegerField(default=30)),
                ('booking_buffer_minutes', models.PositiveIntegerField(default=30)),
                ('notification_email', models.EmailField(default='notifications@auroramotors.com', max_length=254)),
                ('support_email', models.EmailField(default='support@auroramotors.com', max_length=254)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
