# Generated by Django 5.2.4 on 2025-07-07 11:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent for Signature'), ('signed', 'Signed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signature_data', models.JSONField(blank=True, default=dict)),
                ('signature_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_user_agent', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/pdfs/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('signed_pdf_file', models.FileField(blank=True, null=True, upload_to='contracts/signed/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='bookings.booking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_viewers', models.PositiveIntegerField(default=0)),
                ('first_viewed', models.DateTimeField(blank=True, null=True)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('time_to_sign', models.DurationField(blank=True, null=True)),
                ('sign_attempts', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Analytics',
                'verbose_name_plural': 'Contract Analytics',
            },
        ),
        migrations.CreateModel(
            name='ContractAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent for Signature'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('downloaded', 'Downloaded'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('revised', 'Revised')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('additional_data', models.JSONField(blank=True, default=dict)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contracts.contract')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Audit Log',
                'verbose_name_plural': 'Contract Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reminder_date', models.DateTimeField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Reminder',
                'verbose_name_plural': 'Contract Reminders',
                'ordering': ['reminder_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('rental_agreement', 'Rental Agreement'), ('terms_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('damage_waiver', 'Damage Waiver'), ('insurance_agreement', 'Insurance Agreement'), ('additional_driver', 'Additional Driver Agreement')], max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('content', models.TextField(help_text='Use {{variable}} for dynamic content')),
                ('is_active', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=True)),
                ('requires_witness', models.BooleanField(default=False)),
                ('requires_date', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Template',
                'verbose_name_plural': 'Contract Templates',
                'ordering': ['template_type', 'name'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.contracttemplate'),
        ),
        migrations.CreateModel(
            name='ContractRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('change_notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract Revision',
                'verbose_name_plural': 'Contract Revisions',
                'ordering': ['-revision_number'],
                'unique_together': {('contract', 'revision_number')},
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_type', models.CharField(choices=[('customer', 'Customer'), ('witness', 'Witness'), ('staff', 'Staff')], max_length=20)),
                ('signature_data', models.JSONField(default=dict)),
                ('signature_text', models.CharField(blank=True, max_length=200)),
                ('signature_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('verification_code', models.CharField(blank=True, max_length=100)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.contract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Signature',
                'verbose_name_plural': 'Contract Signatures',
                'unique_together': {('contract', 'signer', 'signature_type')},
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', 'created_at'], name='contracts_c_status_efee21_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['user', 'status'], name='contracts_c_user_id_6c12ac_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['booking'], name='contracts_c_booking_877f06_idx'),
        ),
    ]
