# Generated by Django 5.2.4 on 2025-07-07 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('calculation_method', models.CharField(choices=[('sql', 'SQL Query'), ('python', 'Python Function'), ('aggregation', 'Data Aggregation')], max_length=50)),
                ('calculation_config', models.JSONField(default=dict)),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('previous_value', models.FloatField(blank=True, null=True)),
                ('target_value', models.FloatField(blank=True, null=True)),
                ('update_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('format_type', models.CharField(choices=[('number', 'Number'), ('percentage', 'Percentage'), ('currency', 'Currency'), ('duration', 'Duration')], default='number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict)),
                ('widgets', models.JSONField(default=list)),
                ('is_default', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('metric_type', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('histogram', 'Histogram'), ('timer', 'Timer')], max_length=20)),
                ('value', models.FloatField()),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['name', 'timestamp'], name='analytics_m_name_b1e977_idx'), models.Index(fields=['timestamp'], name='analytics_m_timesta_77f16a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('user_activity', 'User Activity'), ('booking_analytics', 'Booking Analytics'), ('vehicle_utilization', 'Vehicle Utilization'), ('revenue_analysis', 'Revenue Analysis'), ('document_compliance', 'Document Compliance'), ('contract_performance', 'Contract Performance'), ('system_performance', 'System Performance'), ('marketing_analysis', 'Marketing Analysis')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('filters', models.JSONField(default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('user', 'User Activity'), ('booking', 'Booking Activity'), ('vehicle', 'Vehicle Activity'), ('document', 'Document Activity'), ('contract', 'Contract Activity'), ('system', 'System Activity'), ('marketing', 'Marketing Activity')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('click', 'Click'), ('download', 'Download'), ('search', 'Search'), ('filter', 'Filter'), ('share', 'Share'), ('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('error', 'Error')], max_length=50)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'action'], name='analytics_a_categor_99427a_idx'), models.Index(fields=['user', 'created_at'], name='analytics_a_user_id_ecb128_idx'), models.Index(fields=['session_key', 'created_at'], name='analytics_a_session_b528aa_idx'), models.Index(fields=['created_at'], name='analytics_a_created_546677_idx')],
            },
        ),
    ]
