# Generated by Django 5.2.4 on 2025-07-07 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='bookingadditionaldriver',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingadditionaldriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_drivers',
            field=models.ManyToManyField(blank=True, related_name='additional_driver_bookings', through='bookings.BookingAdditionalDriver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingextension',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_extensions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookinginvoice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingnote',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='bookings.booking'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingadditionaldriver',
            unique_together={('booking', 'driver')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_date'], name='bookings_bo_status_aeddf5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['vehicle', 'start_date'], name='bookings_bo_vehicle_0189ec_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_number'], name='bookings_bo_booking_03d631_idx'),
        ),
    ]
